services:
  claudecode:
    image: r488it/claude_code
    platform: linux/amd64
    user: root  
    volumes:
      - ${WORKSPACE_PATH}:/workspace
    ports:
      - "9999:9999"
    restart: unless-stopped
    stdin_open: true 

  tavily:
    image: r488it/tavily
    platform: linux/amd64
    restart: unless-stopped
    stdin_open: true 
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}